In [1]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
from sklearn.metrics import confusion_matrix
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np
X,y = make_classification(n_samples=10000,n_features=5,n_informative=2,n_redundant=1,random_state=1)

In [2]:
Xtrain,Xtest,Ytrain,Ytest=train_test_split(X,y,test_size=0.2)
mymodel = Sequential()
mymodel.add(Dense(2,activation='relu',input_dim=5))
mymodel.add(Dense(1,activation='sigmoid'))
mymodel.compile(loss='binary_crossentropy',optimizer='ADAM',metrics=['accuracy'])
mymodel.fit(Xtrain,Ytrain,epochs=10,batch_size=2,verbose=1)

Epoch 1/10
4000/4000 [==============================] - 3s 666us/step - loss: 0.5248 - accuracy: 0.7806
Epoch 2/10
4000/4000 [==============================] - 3s 638us/step - loss: 0.2811 - accuracy: 0.8998
Epoch 3/10
4000/4000 [==============================] - 3s 640us/step - loss: 0.2564 - accuracy: 0.9105
Epoch 4/10
4000/4000 [==============================] - 3s 702us/step - loss: 0.2472 - accuracy: 0.9225
Epoch 5/10
4000/4000 [==============================] - 3s 644us/step - loss: 0.2387 - accuracy: 0.9326
Epoch 6/10
4000/4000 [==============================] - 3s 658us/step - loss: 0.2135 - accuracy: 0.9423
Epoch 7/10
4000/4000 [==============================] - 3s 673us/step - loss: 0.2198 - accuracy: 0.9503
Epoch 8/10
4000/4000 [==============================] - 3s 690us/step - loss: 0.2117 - accuracy: 0.9491
Epoch 9/10
4000/4000 [==============================] - 3s 643us/step - loss: 0.1948 - accuracy: 0.9551
Epoch 10/10
4000/4000 [==============================] - 3s 645u

In [10]:
Ypred = mymodel.predict(Xtest)
YpredF=np.zeros(len(Ytest))
#0.5 Threshold value
for i in range (len(Ytest)):
    if(Ypred[i]>=0.5):
        YpredF[i]=1
    else:
        continue
print(Ytest,"\n",Ypred,"\n",YpredF)
cf = confusion_matrix(Ytest,YpredF)
print(cf)
accuracy = (cf[0][0]+cf[1][1])/(cf[0][0]+cf[0][1]+cf[1][0]+cf[1][1])
print(accuracy*100)

[1 1 0 ... 0 1 1] 
 [[0.00474572]
 [0.85074353]
 [0.22117615]
 ...
 [0.01113573]
 [0.8962306 ]
 [0.8913508 ]] 
 [0. 1. 0. ... 0. 1. 1.]
[[963  28]
 [ 69 940]]
95.15
