In [1]:
#comparing classification algorithms
#1000,10000,100000 examples
#5,10,25,100 features
# affect of binary and multiclass
# change of kernels, params and epochs
# effect of optimization
# effect of feature extraction

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.linear_model import LogisticRegression
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import pandas as pd
import numpy as np

In [2]:
######
#BINARY CLASSIFICATION
#1000 , 10000, 100000
X1,y1 = make_classification(n_samples=1000,n_features=5,n_informative=2,n_redundant=1,random_state=1)
X2,y2 = make_classification(n_samples=10000,n_features=5,n_informative=2,n_redundant=1,random_state=1)
X3,y3 = make_classification(n_samples=100000,n_features=5,n_informative=2,n_redundant=1,random_state=1)

In [3]:
X4,y4 = make_classification(n_samples=10000,n_features=10,n_informative=2,n_redundant=1,random_state=1)
X5,y5 = make_classification(n_samples=10000,n_features=50,n_informative=2,n_redundant=1,random_state=1)
X6,y6 = make_classification(n_samples=10000,n_features=100,n_informative=2,n_redundant=1,random_state=1)

In [4]:
#MULTICLASS CLASSIFICATION
X7,y7 = make_classification(n_samples=10000,n_features=10,n_informative=4,n_redundant=1,random_state=1,n_classes=4)

In [51]:
Datasets=[[X1,y1,"Dataset 1"],
         [X2,y2,"Dataset 2"],
         [X3,y3,"Dataset 3"],
         [X4,y4,"Dataset 4"],
         [X5,y5,"Dataset 5"],
         [X6,y6,"Dataset 6"]]
for r in Datasets:
    Xtrain,Xtest,Ytrain,Ytest=train_test_split(r[0],r[1],test_size=0.2)
    logreg = LogisticRegression(C=1.5,solver="lbfgs")
    logreg.fit(Xtrain,Ytrain)
    Ypred = logreg.predict(Xtest)
    print(r[2])
    print(confusion_matrix(Ytest,Ypred))
    print(classification_report(Ytest,Ypred))
    print("\n=====================================================================")

Dataset 1
[[82 13]
 [16 89]]
              precision    recall  f1-score   support

           0       0.84      0.86      0.85        95
           1       0.87      0.85      0.86       105

    accuracy                           0.85       200
   macro avg       0.85      0.86      0.85       200
weighted avg       0.86      0.85      0.86       200


Dataset 2
[[900 105]
 [142 853]]
              precision    recall  f1-score   support

           0       0.86      0.90      0.88      1005
           1       0.89      0.86      0.87       995

    accuracy                           0.88      2000
   macro avg       0.88      0.88      0.88      2000
weighted avg       0.88      0.88      0.88      2000


Dataset 3
[[9251  798]
 [ 925 9026]]
              precision    recall  f1-score   support

           0       0.91      0.92      0.91     10049
           1       0.92      0.91      0.91      9951

    accuracy                           0.91     20000
   macro avg       0.91    

In [55]:
Datasets=[[X1,y1,"Dataset 1"],
         [X2,y2,"Dataset 2"],
         [X3,y3,"Dataset 3"],
         [X4,y4,"Dataset 4"],
         [X5,y5,"Dataset 5"],
         [X6,y6,"Dataset 6"]]
for r in Datasets:
    Xtrain,Xtest,Ytrain,Ytest=train_test_split(r[0],r[1],test_size=0.2)
    mymodel = Sequential()
    mymodel.add(Dense(2,activation='relu',input_dim=5))
    mymodel.add(Dense(1,activation='sigmoid'))
    mymodel.compile(loss='binary_crossentropy',optimizer='ADAM',metrics=['accuracy'])
    mymodel.fit(Xtrain,Ytrain,epochs=10,batch_size=2,verbose=0)
    Ypred = mymodel.predict(Xtest)
    YpredF=np.zeros(len(Ytest))
    #0.5 Threshold value
    for i in range (len(Ytest)):
        if(Ypred[i]>=0.5):
            YpredF[i]=1
        else:
            continue
    print(r[2])
    print(confusion_matrix(Ytest,YpredF))
    print(classification_report(Ytest,YpredF))
    print("\n=====================================================================")

Dataset 1
[[79 12]
 [12 97]]
              precision    recall  f1-score   support

           0       0.87      0.87      0.87        91
           1       0.89      0.89      0.89       109

    accuracy                           0.88       200
   macro avg       0.88      0.88      0.88       200
weighted avg       0.88      0.88      0.88       200


Dataset 2
[[984  21]
 [ 68 927]]
              precision    recall  f1-score   support

           0       0.94      0.98      0.96      1005
           1       0.98      0.93      0.95       995

    accuracy                           0.96      2000
   macro avg       0.96      0.96      0.96      2000
weighted avg       0.96      0.96      0.96      2000


Dataset 3
[[9228  861]
 [ 786 9125]]
              precision    recall  f1-score   support

           0       0.92      0.91      0.92     10089
           1       0.91      0.92      0.92      9911

    accuracy                           0.92     20000
   macro avg       0.92    

ValueError: in user code:

    C:\Users\HARSHIT\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:805 train_function  *
        return step_function(self, iterator)
    C:\Users\HARSHIT\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:795 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\HARSHIT\anaconda3\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1259 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\HARSHIT\anaconda3\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2730 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\HARSHIT\anaconda3\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:3417 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\HARSHIT\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:788 run_step  **
        outputs = model.train_step(data)
    C:\Users\HARSHIT\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:754 train_step
        y_pred = self(x, training=True)
    C:\Users\HARSHIT\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:998 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    C:\Users\HARSHIT\anaconda3\lib\site-packages\tensorflow\python\keras\engine\input_spec.py:259 assert_input_compatibility
        ' but received input with shape ' + display_shape(x.shape))

    ValueError: Input 0 of layer sequential_10 is incompatible with the layer: expected axis -1 of input shape to have value 5 but received input with shape (2, 10)
